name: Workflow PR Validate Tag

on:
  pull_request:
    branches: [main, develop]

jobs:
  Pull_Request:
    name: PR
    uses: juv-dev/workflows-frontend/.github/workflows/frontend-pr-validate-tag.yml@main
